In [ ]:
import pandas as pd

df = pd.read_csv('new_data.csv')
df = df.drop(columns=['Cost'], errors='ignore')
df['Contrast'] = False
df.head()

# df.to_excel('new_data.xlsx', index=False)

,Patient_ID,Age,Gender,Condition,Procedure,Length_of_Stay,Readmission,Outcome,Satisfaction,Contrast
0,1001,31,Male,Femur Fracture,X-Ray Femur,5,No,Improved,2,False
1,1002,45,Female,Uterine Fibroids,MRI-Uterus,1,No,Improved,4,False
2,1003,25,Male,Hand Fracture,X-Ray Hand,1,Yes,Stable,4,False
3,1004,75,Male,Prostate Check,MRI-Prostate,4,Yes,Recovered,4,False
4,1005,67,Male,Stroke,CT-Brain Helical,9,No,Recovered,3,False

In [10]:
import pandas as pd

df = pd.read_excel('new_data.xlsx', engine='openpyxl')
df = df.drop(columns=['Cost'], errors='ignore')
df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Length_of_Stay,Readmission,Outcome,Satisfaction,Contrast
0,1001,31,Male,Femur Fracture,X-Ray Femur,5,No,Improved,2,False
1,1002,45,Female,Uterine Fibroids,MRI-Uterus,1,No,Improved,4,False
2,1003,25,Male,Hand Fracture,X-Ray Hand,1,Yes,Stable,4,False
3,1004,75,Male,Prostate Check,MRI-Prostate,4,Yes,Recovered,4,True
4,1005,67,Male,Stroke,CT-Brain Helical,9,No,Recovered,3,False

In [11]:
from faker import Faker
import pandas as pd

fake = Faker()

# Function to generate a birthdate for a given age
def get_birthdate(age):
    return fake.date_of_birth(minimum_age=age, maximum_age=age)

# Apply the function to each row in the Age column
df['Birthdate'] = df['Age'].apply(get_birthdate)

df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Length_of_Stay,Readmission,Outcome,Satisfaction,Contrast,Birthdate
0,1001,31,Male,Femur Fracture,X-Ray Femur,5,No,Improved,2,False,1993-07-07
1,1002,45,Female,Uterine Fibroids,MRI-Uterus,1,No,Improved,4,False,1979-08-16
2,1003,25,Male,Hand Fracture,X-Ray Hand,1,Yes,Stable,4,False,2000-05-18
3,1004,75,Male,Prostate Check,MRI-Prostate,4,Yes,Recovered,4,True,1949-08-09
4,1005,67,Male,Stroke,CT-Brain Helical,9,No,Recovered,3,False,1957-10-28

In [12]:
fake = Faker('nl_NL')  # Dutch locale

def get_first_name(gender):
    if gender == 'Male':
        return fake.first_name_male()
    if gender == 'Female':
        return fake.first_name_female()
    

def get_last_name():
    return fake.last_name()

# Assuming df is already loaded and has a 'Gender' column
df['First_Name'] = df['Gender'].apply(get_first_name)
df['Last_Name'] = df['Gender'].apply(lambda x: get_last_name())

df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Length_of_Stay,Readmission,Outcome,Satisfaction,Contrast,Birthdate,First_Name,Last_Name
0,1001,31,Male,Femur Fracture,X-Ray Femur,5,No,Improved,2,False,1993-07-07,Hugo,van der Horst
1,1002,45,Female,Uterine Fibroids,MRI-Uterus,1,No,Improved,4,False,1979-08-16,Femke,Freshour
2,1003,25,Male,Hand Fracture,X-Ray Hand,1,Yes,Stable,4,False,2000-05-18,Brent,Demmendaal
3,1004,75,Male,Prostate Check,MRI-Prostate,4,Yes,Recovered,4,True,1949-08-09,Lukas,Aschman
4,1005,67,Male,Stroke,CT-Brain Helical,9,No,Recovered,3,False,1957-10-28,Fabian,van der Steen

In [14]:
# Reorder columns in df: patient_ID, First_Name, Last_Name, Gender, Birthdate, and the rest
cols = list(df.columns)
# Find the rest of the columns except the specified ones
main_cols = ['Patient_ID', 'First_Name', 'Last_Name', 'Gender', 'Birthdate']
rest_cols = [col for col in cols if col not in main_cols]
# Reorder
df = df[main_cols + rest_cols]

df.head()

,Patient_ID,First_Name,Last_Name,Gender,Birthdate,Age,Condition,Procedure,Length_of_Stay,Readmission,Outcome,Satisfaction,Contrast
0,1001,Hugo,van der Horst,Male,1993-07-07,31,Femur Fracture,X-Ray Femur,5,No,Improved,2,False
1,1002,Femke,Freshour,Female,1979-08-16,45,Uterine Fibroids,MRI-Uterus,1,No,Improved,4,False
2,1003,Brent,Demmendaal,Male,2000-05-18,25,Hand Fracture,X-Ray Hand,1,Yes,Stable,4,False
3,1004,Lukas,Aschman,Male,1949-08-09,75,Prostate Check,MRI-Prostate,4,Yes,Recovered,4,True
4,1005,Fabian,van der Steen,Male,1957-10-28,67,Stroke,CT-Brain Helical,9,No,Recovered,3,False